package com.dikshant.io.food.delivery.exception;

public enum ExceptionType {

    RESTAURANT_ALREADY_EXISTS,
    RESTAURANT_NOT_FOUND,
    MENU_NOT_FOUND,
    MENU_ALREADY_EXISTS,
    MENU_ITEM_NOT_FOUND,
    CART_IS_EMPTY,
    INVALID_ORDER,
    ORDER_NOT_FOUND,
    ORDER_NOT_CONFIRMED,
    USER_ALREADY_EXISTS,
    USER_NOT_FOUND,
    PAYMENT_NOT_EXISTS,
    DELIVERY_ALREADY_EXISTS,
    DELIVERY_NOT_FOUND
}
